### ISSUE TITLE
(Still exists with Nimble 0.16.2) https://github.com/arnetheduck/nph/issues/84#issue-2562831106

### ISSUE THREAD

**Issue by jaymanmdev** [arnetheduck/nph#85]
![image](https://github.com/user-attachments/assets/bc4ecdca-09db-4ca9-aa89-9b2e0e60dda3)

I am just starting with nim and am setting up my dev environment, however, I can't get nph installed as I am encountering this weird issue. I saw the issue linked in the title and saw that 0.16.2 that just released should have fixed it.
I upgraded nimble with `nimble install nimble` (as nim comes with 0.16.1) and the issue persists.
It hasn't been an easy process to get Nim setup unfortunately...
Any ideas?

**Comment by arnetheduck** [comment]
generally, nph doesn't build with nim 2.2 (it needs 2.0.x specifically) because of changes in the compiler - this however doesn't affect its ability to format code (that later will be compiled with 2.2) - nimble 0.16.2 (should) know this and use the correct nim version - if it doesn't, it's useful to report a bug in the nimble repo that shows what commands you ran and what the output was.
